/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Funcionario;

/**
 *
 * @author jhona
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private TelaInicial telaInicial;
    private Funcionario f = new Funcionario("Edgar", 123, 2, "SD");
    private ArrayList<Funcionario> f1 = new ArrayList<Funcionario>();
    private Funcionario f2 = new Funcionario("jhonathan", 234, 2, "SG");
    private Funcionario f3 = new Funcionario("jailson", 235, 2, "CB");
    private Funcionario f4 = new Funcionario("Pedro", 222, 2, "CB");
    private Funcionario f5 = new Funcionario("Islando", 1, 1, "SD");
    private Funcionario f6 = new Funcionario("Soares", 2, 2, "SG");
    private Funcionario f7 = new Funcionario("Romulo", 3, 3, "SO");
    private Funcionario f8 = new Funcionario("Afonso", 4, 4, "SO");
    private Funcionario f9 = new Funcionario("Lucio", 5, 5, "CB");
    private Funcionario f10 = new Funcionario("Fabricio", 6, 6, "SD");
    private Funcionario f11 = new Funcionario("Tarcisio", 7, 7, "SO");
    private Funcionario f12 = new Funcionario("Max", 8, 8, "CB");
    private Funcionario f13 = new Funcionario("Alekson", 9, 9, "CB");
    private Funcionario f14 = new Funcionario("Eduardo", 10, 10, "SD");
    private Funcionario f15 = new Funcionario("Serra", 11, 11, "CB");
    private Funcionario f16 = new Funcionario("Cosme", 12, 12, "SD");
    private Funcionario f17 = new Funcionario("Saraiva", 13, 13, "CB");
    private Funcionario f18 = new Funcionario("Aurenir", 14, 14, "SO");
    private Funcionario f19 = new Funcionario("Monteiro", 15, 15, "CB");
    private Funcionario f20 = new Funcionario("Ana", 16, 16, "SO");
                     
     

    /**
     * Creates new form TelaInicial
     */
    public TelaLogin() {
        initComponents();
        f.cadFuncionario(f);
        f.cadFuncionario(f2);
        f.cadFuncionario(f3);
        f.cadFuncionario(f4);
        f.cadFuncionario(f5);
        f.cadFuncionario(f6);
        f.cadFuncionario(f7);
        f.cadFuncionario(f8);
        f.cadFuncionario(f9);
        f.cadFuncionario(f10);
        f.cadFuncionario(f11);
        f.cadFuncionario(f12);
        f.cadFuncionario(f13);
        f.cadFuncionario(f14);
        f.cadFuncionario(f15);
        f.cadFuncionario(f16);
        f.cadFuncionario(f17);
        f.cadFuncionario(f18);
        f.cadFuncionario(f19);
        f.cadFuncionario(f20);
                         
                     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELA DE LOGIN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(72, 72, 103));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de Detalhe Semanal de Serviço(SISDESV)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(332, 332, 332))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(72, 72, 103));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pessoa_1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Senha1.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SENHA");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton1.setText("ENTRAR");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(651, 651, 651)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/captania.png"))); // NOI18N

        jLabel7.setText("V. 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(457, 457, 457))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String senha = String.valueOf(jPasswordField1.getPassword());
       // Funcionario f3;
       
       ArrayList<Funcionario> array = new ArrayList<Funcionario>();
       
       array = f.buscaFuncionarios();
      
       try{
       
       int nip = Integer.parseInt(jTextField1.getText());
       
       int x = 0;
       
       
        for(Funcionario f3 : array){
            x++;
            System.out.println(f3.getNip());
            if(f3.getNip() == nip && senha.equals("admin")){
                f3.logar(f3);
                  f3.setTipo("admin");
                JOptionPane.showMessageDialog(null, "Bem Vindo ao Sistema!");
                telaInicial = new TelaInicial();
                telaInicial.setVisible(true);
                dispose();
                break;
            }
            if(nip != f3.getNip() && array.size() == x){
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
                break;
            }
            
            if(f3.getNip() == nip && senha.equals("cpma")){
                f3.logar(f3);
                f3.setTipo("funcionario");
                JOptionPane.showMessageDialog(null, "Bem Vindo ao Sistema!");
               TelaInicialF telaInicial = new TelaInicialF();
                telaInicial.setVisible(true);
                dispose();
                break;
            }
            if(nip != f3.getNip() && array.size() == x){
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
            }
            
            
            
        }
        
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "DIGITE APENAS NUMERO NO LOGIN!");
       }
    
        /*if(jTextField1.getText().equals("admin") && senha.equals("admin")){
            f.logar(f);
             JOptionPane.showMessageDialog(null, "Bem Vindo ao Sistema!");
             telaInicial = new TelaInicial();
             telaInicial.setVisible(true);
             dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro no Login ou senha!");
        }
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
      
        
        
        
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
     
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
       String senha = String.valueOf(jPasswordField1.getPassword());
       // Funcionario f3;
       
       ArrayList<Funcionario> array = new ArrayList<Funcionario>();
       
       array = f.buscaFuncionarios();
      
       try{
       
       int nip = Integer.parseInt(jTextField1.getText());
       
       int x = 0;
       
       
        for(Funcionario f3 : array){
            x++;
            System.out.println(f3.getNip());
            if(f3.getNip() == nip && senha.equals("admin")){
                f3.logar(f3);
                  f3.setTipo("admin");
                JOptionPane.showMessageDialog(null, "Bem Vindo ao Sistema!");
                telaInicial = new TelaInicial();
                telaInicial.setVisible(true);
                dispose();
                break;
            }
            if(nip != f3.getNip() && array.size() == x){
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
                break;
            }
            
            if(f3.getNip() == nip && senha.equals("cpma")){
                f3.logar(f3);
                f3.setTipo("funcionario");
                JOptionPane.showMessageDialog(null, "Bem Vindo ao Sistema!");
               TelaInicialF telaInicial = new TelaInicialF();
                telaInicial.setVisible(true);
                dispose();
                break;
            }
            if(nip != f3.getNip() && array.size() == x){
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
            }
            
            
            
        }
        
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "DIGITE APENAS NUMERO NO LOGIN!");
       }
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       String senha = String.valueOf(jPasswordField1.getPassword());
       // Funcionario f3;
       
       ArrayList<Funcionario> array = new ArrayList<Funcionario>();
       
       array = f.buscaFuncionarios();
      
       try{
       
       int nip = Integer.parseInt(jTextField1.getText());
       
       int x = 0;
       
       
        for(Funcionario f3 : array){
            x++;
            System.out.println(f3.getNip());
            if(f3.getNip() == nip && senha.equals("admin")){
                f3.logar(f3);
                  f3.setTipo("admin");
                JOptionPane.showMessageDialog(null, "Bem Vindo ao Sistema!");
                telaInicial = new TelaInicial();
                telaInicial.setVisible(true);
                dispose();
                break;
            }
            if(nip != f3.getNip() && array.size() == x){
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
                break;
            }
            
            if(f3.getNip() == nip && senha.equals("cpma")){
                f3.logar(f3);
                f3.setTipo("funcionario");
                JOptionPane.showMessageDialog(null, "Bem Vindo ao Sistema!");
               TelaInicialF telaInicial = new TelaInicialF();
                telaInicial.setVisible(true);
                dispose();
                break;
            }
            if(nip != f3.getNip() && array.size() == x){
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
            }
            
            
            
        }
        
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "DIGITE APENAS NUMERO NO LOGIN!");
       }
        
        /*
        if(jTextField1.getText().equals("admin") && senha.equals("admin")){
            f.logar(f);
             JOptionPane.showMessageDialog(null, "Bem Vindo ao Sistema!");
             telaInicial = new TelaInicial();
             telaInicial.setVisible(true);
             dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro no Login ou senha!");
        }*/
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
